print("****************************************")
print("Tugas 1 Kelas B")
print("****************************************")
print("Nama : Kinanthi Putri Ariyani")
print("NPM : 21083010047")
print("****************************************")
print("Notes :")
print("****************************************")
print("Halo dunia!")
print("Ini adalah skrip Bash pertamaku di Linux!")
